version: '3.4'

services:
  contosouniversity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "8800:5000"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro